#!/bin/bash

OPTIONS="-Dactivemq.data=/var/lib/apache-activemq -Dactivemq.brokerName=$HOSTNAME -Dsun.rmi.transport.tcp.responseTimeout=180000"

export STDOUT_DEST="/var/log/apache-activemq/apache-activemq.out"
export STDERR_DEST="/var/log/apache-activemq/apache-activemq.err"

start() {

    nohup /usr/share/apache-activemq/bin/activemq ${OPTIONS} start > ${STDOUT_DEST} 2> ${STDERR_DEST} &

    ## TODO: add wait-for-port 61616 here so that we can verify that ActiveMQ
    # was running.

    wait-for-port --port=61616

}

stop() {

    # attempt a graceful shutdown.

    echo "Stopping ActiveMQ with JMX options: ${OPTIONS}"

    /usr/share/apache-activemq/bin/activemq ${OPTIONS} stop

    # TODO: kill -9 the daemon at this point if the above command fails.

}

restart() {

    stop
    start

}

case $1 in

    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1

esac