#!/bin/bash

OPTIONS="-Dactivemq.data=/var/lib/apache-activemq -Dactivemq.brokerName=$HOSTNAME"

export STDOUT_DEST="/var/log/apache-activemq/apache-activemq.out"
export STDERR_DEST="/var/log/apache-activemq/apache-activemq.err"

start() {

    nohup /usr/share/apache-activemq/bin/activemq $OPTIONS start > $STDOUT_DEST 2> $STDERR_DEST &

}

stop() {

    /usr/share/apache-activemq/bin/activemq $OPTIONS stop

}

restart() {

    stop
    start

}

case $1 in

    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1

esac